### ISSUE TITLE
Beta Announcement

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/wedeploy.com#204]
- [x] [Newsletter](https://app.intercom.io/a/apps/ocvh9014/engage/messages/manual/118328900)
- [x] [Blog Post](https://github.com/wedeploy/wedeploy.com/pull/214)
- [x] Tweet
- [x] [Illustration](https://projects.invisionapp.com//share/2DCEL9M9P#/screens/241694162)
